services:

  mongo:
    container_name: mongo-database
    image: mongo:6.0.3
    volumes:
      - ./data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  library:
    container_name: library-app
    image: node:19.1-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - $LIBRARY_EXTERNAL_PORT:$LIBRARY_INTERNAL_PORT
    environment:
      - LIBRARY_INTERNAL_PORT=$LIBRARY_INTERNAL_PORT
      - MONGODB_SERVICE_NAME=$MONGODB_SERVICE_NAME
      - MONGODB_INTERNAL_PORT=$MONGODB_INTERNAL_PORT
      - MONGODB_LOGIN=$MONGODB_LOGIN
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$DB_NAME
    command: [ "npm", "run", "start:dev" ]
    depends_on:
      - mongo

  mongo-express:
    container_name: mongo-admin-panel
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - $MONGO_ADMIN_PANEL_EXTERNAL_PORT:$MONGO_ADMIN_PANEL_INTERNAL_PORT
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_LOGIN
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_LOGIN:$MONGODB_PASSWORD@$MONGODB_SERVICE_NAME:$MONGODB_INTERNAL_PORT/
    depends_on:
      - mongo
      - library